### ISSUE TITLE
Cannot extract or mount nvme partition

### ISSUE THREAD

**Issue by hatesigningup** [fiddyschmitt/clonezilla-util#13]
After hours of swearing and biting all my nails off I managed to get the command working (had to give it a filename on the command line, NOT a folder name!), it ran through and then spat out the "Insufficient system resources" error:

```
D:\>dir
 Volume in drive D is CloneZilla
 Volume Serial Number is 4B6C-3A28

 Directory of D:\

18/09/2022  01:40 PM    <DIR>          .Trash-1000
10/06/2022  03:47 PM    <DIR>          2022-06-10-11-Lenovo-Win11-img
18/09/2022  07:55 PM    <DIR>          clonezilla-util.v1.8.0.win-x64
18/09/2022  07:53 PM    <DIR>          logs
               0 File(s)              0 bytes
               4 Dir(s)  1,489,747,136,512 bytes free

D:\>D:\clonezilla-util.v1.8.0.win-x64\clonezilla-util.exe extract-partition-image --input D:\2022-06-10-11-Lenovo-Win11-img\nvme0n1p3.ntfs-ptcl-img.zst.aa --output D:\
[20:15:48 INF] clonezilla-util v1.8.0
[20:15:49 INF] Waiting for Z:\ to be available.
[20:15:59 INF] nvme0n1p3.ntfs-ptcl-img.zst uses Zstandard compression, which is not seekable. Extracting first.
[20:15:59 INF] Using cached file: D:\clonezilla-util.v1.8.0.win-x64\cache\b49f5eea737c11da41510b3dc3fd8602\cache.train
[20:16:07 INF] [] [] Reading partclone content map
Unhandled exception. System.Exception: D:\clonezilla-util.v1.8.0.win-x64\ext\7-Zip\win-x64\7z.exe l -slt "Z:\ca78edff-0e48-4c3d-a9ca-e2defd77e860 - Temp\3fd4c70b-7d36-48d6-b174-9a2da2bb7fd4\9332339d-cdb2-4939-8d1c-d3b40b8a5ade"
Process encountered errors:
ERROR: Z:\ca78edff-0e48-4c3d-a9ca-e2defd77e860 - Temp\3fd4c70b-7d36-48d6-b174-9a2da2bb7fd4\9332339d-cdb2-4939-8d1c-d3b40b8a5ade : opening : Insufficient system resources exist to complete the requested service.


System ERROR:
Insufficient system resources exist to complete the requested service.
   at libCommon.ProcessUtility.RunCommand(String cpath, String args, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`2 shouldStop)+MoveNext()
   at lib7Zip.SevenZipUtility.GetArchiveEntries(String archiveFilename, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`1 shouldStop)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 , Boolean& )
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ImageFiles.RawImage.SetupFromStream(Stream rawImageStream, IEnumerable`1 archiveEntries, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ImageFiles.CompressedImage..ctor(String filename, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, Folder tempFolder)
   at libClonezilla.PartitionContainers.ImageFiles.ImageFile..ctor(String filename, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.ExtractPartitionImage(ExtractPartitionImage extractPartitionImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

D:\>
```

The partition image is nearly 1 terabyte in size and clonezilla-util has created a cache file on my D: drive which still has 1.35 TB free.

Any ideas how to fix this?

Thanks.

EDIT1:  I also tried to use the --mount function, but the result was exactly the same.

Command line examples:
D:\clonezilla-util.v1.8.0.win-x64\clonezilla-util.exe extract-partition-image --input D:\2022-06-10-11-Lenovo-Win11-img\nvme0n1p3.ntfs-ptcl-img.zst.aa --output D:\

D:\clonezilla-util.v1.8.0.win-x64\clonezilla-util.exe mount-as-image-files --input D:\2022-06-10-11-Lenovo-Win11-img\nvme0n1p3.ntfs-ptcl-img.zst.aa --mount L:\

EDIT2: The laptop I'm using only has 16 GB RAM, I'm going to try again on a machine with 32 GB, see if that helps :).

EDIT3: No, 32g made no difference, but I did notice that the temporarily created Z: drive had 8.43TB of 9.37TB free:

![2022-09-18a](https://user-images.githubusercontent.com/49374664/190918722-b2481e4a-b5b4-44c5-addf-6a0fd791d59d.png)

**Comment by fiddyschmitt** [comment]
Hello!

Thanks for the comprehensive feedback, particularly when you hate signups :)

The new version I just released ([1.8.1](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v1.8.1)) should fix this issue. Please point to the _folder_ rather than file, so the program correctly opens your nvme0n1p3 partition (which appears to be split into multiple files). So please use:

`clonezilla-util.exe extract-partition-image --input "D:\2022-06-10-11-Lenovo-Win11-img" --output D:\ -p nvme0n1p3`

Please let me know how it goes :)

Cheers,
Fidel

**Comment by hatesigningup** [comment]
Haha, no worries and many thanks to you for creating this extremely useful piece of software.

I tried using the folder path to start with, but it would never do anything at all, only give me an error - maybe because I never added the "-p nvme0n1p3" part on the end - I never even saw that option!

That's when I eventually found out that if I gave it a filename, it would actually start - even though it ultimately failed ;).

I eventually managed to actually get Clonezilla to unpack the files, which calmed my nerves.  I was panicking thinking the backup files were corrupt.

I'll give it a try later on tonight or tomorrow, I've spent (wasted!!) the last two whole days copying and backing up files from multiple hard disks - it's driving me nuts.

Kind regards,  Kev :).

**Comment by fiddyschmitt** [comment]
Thanks! :)

The `-p nvme0n1p3` just tells it which partition to extract. If no `-p` option is provided, it extracts all partitions.

If you get a chance, could you please post the contents of the file called `parts`?
Also, a screenshot of the folder please. (I'd like to see if the partitions are compressed & split).

Haha apologies for the panic! Glad your backup is okay.

Cheers,
Fidel

**Comment by hatesigningup** [comment]
Parts file - 
nvme0n1p1 nvme0n1p2 nvme0n1p3 nvme0n1p4

Blkdev.list file -
KNAME     NAME          SIZE TYPE FSTYPE      MOUNTPOINT                                     MODEL
loop0     loop0       252.3M loop squashfs    /usr/lib/live/mount/rootfs/filesystem.squashfs 
sda       sda         119.1G disk                                                                       STORAGE_DEVICE
sda1      |-sda1      100.1G part exfat                                                      
sda2      |-sda2         32M part iso9660                                                    
sda3      `-sda3         19G part ntfs                                                       
sdb       sdb           1.8T disk ext4        /home/partimag                                 WDC_WD20EZRX-00D8PB0
nvme1n1   nvme1n1     931.5G disk                                                            Samsung SSD 970 EVO 1TB
nvme1n1p1 |-nvme1n1p1   512M part vfat                                                       
nvme1n1p2 |-nvme1n1p2   1.7G part ext4                                                       
nvme1n1p3 `-nvme1n1p3 929.3G part crypto_LUKS                                                
nvme0n1   nvme0n1     953.9G disk                                                            SKHynix_HFS001TDE9X084N
nvme0n1p1 |-nvme0n1p1   260M part vfat                                                       
nvme0n1p2 |-nvme0n1p2    16M part                                                            
nvme0n1p3 |-nvme0n1p3 951.6G part ntfs                                                       
nvme0n1p4 `-nvme0n1p4     2G part ntfs                                                       


And here the screenshots -


![2022-09-20](https://user-images.githubusercontent.com/49374664/191226113-11dd581e-df1f-489f-8c32-5d6b3fe2c9d2.png)



![2022-09-20e](https://user-images.githubusercontent.com/49374664/191226172-8b10f9c9-2ccb-45ca-8f46-43f67e5c8a7c.png)


The directory listing was so long I had to stitch four screenshots together!

Hope that helps.

Regards :).

**Comment by hatesigningup** [comment]
Hmm, still get errors when I give the folder name - 


```
Microsoft Windows [Version 10.0.19044.2006]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Kev>C:\users\kev\Downloads\clonezilla-util.v1.8.1.win-x64\clonezilla-util.exe mount-as-image-files --input "E:\2022-06-10-11-Lenovo-Win11-img" --mount L:\
[11:56:30 INF] clonezilla-util v1.8.1
Unhandled exception. System.Exception: Could not determine if this is a Clonezilla folder, or a partclone file: E:\2022-06-10-11-Lenovo-Win11-img
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsImageFiles(MountAsImageFiles mountAsImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

C:\Users\Kev>C:\users\kev\Downloads\clonezilla-util.v1.8.1.win-x64\clonezilla-util.exe mount --input "E:\2022-06-10-11-Lenovo-Win11-img" --mount L:\
[11:58:29 INF] clonezilla-util v1.8.1
Unhandled exception. System.Exception: Could not determine if this is a Clonezilla folder, or a partclone file: E:\2022-06-10-11-Lenovo-Win11-img
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

C:\Users\Kev>C:\users\kev\Downloads\clonezilla-util.v1.8.1.win-x64\clonezilla-util.exe mount --input "E:\2022-06-10-11-Lenovo-Win11-img"  -p nvme0n1p3 --mount L:\
[12:00:11 INF] clonezilla-util v1.8.1
Unhandled exception. System.Exception: Could not determine if this is a Clonezilla folder, or a partclone file: E:\2022-06-10-11-Lenovo-Win11-img
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

C:\Users\Kev>

```
Am I doing something wrong?

Regards :).

**Comment by fiddyschmitt** [comment]
Epic feedback - you're the best!!

Your folder appears to be missing a couple of key files:

`clonezilla-img` The presence of this file (content doesn't matter) is what the program uses to determine if the folder is a Clonezilla folder.
`Info-img-id.txt` The contents of this file are used to uniquely identify the folder (for caching purposes).

Without them the program will crash as you've seen.

To get it working, please create:

`clonezilla-img` This has not extension, and doesn't need content.
`Info-img-id.txt` Created with notepad is fine, with the following content:

```
# This checksum is only for identifying the image. Created by the command: sha512sum clonezilla-img
IMG_ID=ae8f8dd2638d1aee6e97631c4d2e46ebb536b64f67ae6778aa6b3cecab2e679180efe66433bacb29620c9ae20e6ae132526facf949e19d912039663d1e0ad9f1
```

Then if you re-run the commands, they should work.

Please let me know if that works.

Thanks!
Fidel

**Comment by hatesigningup** [comment]
Woohoo, that worked!  It took nearly 3 hours to finish, but it mounted the image and I could browse it's contents.

I've no idea why those config files were missing, very strange.  I also have a backup from the second linux hard disk that was in that laptop, and the files are present.

Many thanks for all your help and patience, it's much appreciated.  And thanks for all your hard work on this tool, again very much appreciated.

Kind regards, Kev.

**Comment by fiddyschmitt** [comment]
Woohoo! Nice!!

Thanks Kev, my pleasure! Really appreciate your quick & detailed responses - that's rare these days!
